//! # Lumi IPC — Inter-Process Communication Framework
//!
//! The `lumi-ipc` crate is the **sole communication infrastructure** for the Lumi
//! desktop AI companion platform. Every process (Core, Render, Voice, Storage,
//! Plugin Host) communicates exclusively through this framework. No process may
//! open a raw socket, pipe, or shared memory segment outside of `lumi-ipc`.
//!
//! ## Architecture: The Three Transport Tiers
//!
//! Not all channels should use the same transport. Selecting the wrong transport
//! for a channel's latency/throughput profile degrades the entire system.
//! `lumi-ipc` implements three distinct transport tiers:
//!
//! ### Tier 1 — Shared Memory Ring Buffer (sub-100µs)
//!
//! For channels where latency is sub-millisecond and both processes share memory:
//! `render.command`, `ai.state`. Uses a lock-free SPSC ring buffer in a shared
//! memory region (`mmap` on Unix, `CreateFileMapping` on Windows). Zero
//! serialization overhead — processes write directly into the shared region using
//! a pre-agreed schema.
//!
//! **Safety invariants:** Every shared memory region carries a `magic` sentinel,
//! a `schema_hash` (FNV of the message type layout), and uses `SeqCst` ordering
//! for head/tail atomics. All `unsafe` blocks have formal safety comments.
//!
//! ### Tier 2 — Unix Domain Socket / Named Pipe (< 1ms)
//!
//! For channels where structured typed messages are exchanged at moderate rates:
//! `memory.write`, `memory.query`, `plugin.invoke`, `voice.output`. Uses Tokio
//! async I/O, MessagePack serialization, length-prefixed framing. Automatic
//! reconnection with exponential backoff.
//!
//! ### Tier 3 — In-Process Channel (nanoseconds)
//!
//! For `desktop.event` which is Core-to-Core (internal subsystem communication
//! in the same process). Uses `tokio::sync::broadcast` or `tokio::sync::mpsc`
//! directly, bypassing all serialization and transport overhead.
//!
//! ## The Transport Trait
//!
//! The [`Transport`] trait abstracts over all three tiers. The [`ChannelRouter`]
//! selects the appropriate transport tier at channel registration time based on
//! the channel's declared properties.
//!
//! ## Channel Topology
//!
//! The following table defines the authoritative channel topology for the Lumi
//! platform. Each channel's transport, backpressure policy, and latency budget
//! are encoded at compile time.
//!
//! | Channel Name | Publisher(s) | Subscriber(s) | Pattern | Rate | Budget | Tier |
//! |---|---|---|---|---|---|---|
//! | `ai.state` | Core | Render | Pub/Sub | ~10/s | < 5ms | 1 — SHM |
//! | `render.command` | Core | Render | Command | 60/s | < 2ms | 1 — SHM |
//! | `render.input` | Render | Core | Event | Burst | < 10ms | 2 — Socket |
//! | `voice.input` | Voice | Core | Stream | Continuous | < 50ms | 2 — Socket |
//! | `voice.output` | Core | Voice | Stream | Per-sentence | < 100ms | 2 — Socket |
//! | `memory.write` | Core | Storage | Req/Res | ~5/s | < 100ms | 2 — Socket |
//! | `memory.query` | Core | Storage | Req/Res | ~20/s | < 80ms | 2 — Socket |
//! | `desktop.event` | Core | Core | Event | Burst | < 20ms | 3 — InProc |
//! | `plugin.capability` | PH | Core | Req/Res | Startup | < 500ms | 2 — Socket |
//! | `plugin.invoke` | Core | PH | Req/Res | On-demand | < 10s | 2 — Socket |
//!
//! ## Security Model
//!
//! Process authentication uses **HMAC-SHA256** over the message header + payload,
//! keyed with a process-pair shared secret established during the ECDH handshake.
//! Every authenticated message includes a monotonic sequence number for replay
//! attack prevention. Process tokens are single-session only, generated by Core
//! at launch and distributed via one-time secure OS pipes.
//!
//! ## Worked Example
//!
//! ```rust,ignore
//! use lumi_ipc::prelude::*;
//!
//! // 1. Create and configure the message bus
//! let mut bus = MessageBus::new(ProcessId::Core);
//!
//! // 2. Start the bus
//! bus.start().await?;
//!
//! // 3. Subscribe to a channel
//! let mut rx = bus.subscribe(Channel::AiState);
//!
//! // 4. Send a message
//! bus.send(LumiMessage::new_event(
//!     ProcessId::Core,
//!     Channel::AiState,
//!     serde_json::json!({"state": "thinking"}),
//! )?)?;
//!
//! // 5. Receive the message
//! match bus.recv().await {
//!     Some(msg) => println!("Received: {:?}", msg),
//!     None => println!("Bus closed"),
//! }
//! ```
//!
//! ## Crate Structure
//!
//! | Module | Description |
//! |--------|-------------|
//! | [`auth`] | Process authentication, MAC verification, key exchange |
//! | [`bus`] | Central message bus coordinator |
//! | [`codec`] | Tokio-util Codec implementation for framing |
//! | [`config`] | IPC configuration (channels, heartbeats, rate limits) |
//! | [`connection`] | Connection manager with reconnect policy |
//! | [`diagnostics`] | Diagnostics and visualization |
//! | [`discovery`] | Service discovery and registry |
//! | [`dispatcher`] | Message dispatch to subscribers |
//! | [`error`] | IPC error types |
//! | [`event`] | Bus events for monitoring |
//! | [`guard`] | Guards and validation |
//! | [`heartbeat`] | Heartbeat engine, peer health monitoring |
//! | [`manager`] | IPC manager for application integration |
//! | [`message`] | Message type definitions and payloads |
//! | [`metrics`] | IPC metrics integration |
//! | [`middleware`] | Middleware pipeline |
//! | [`peer`] | Peer registry and management |
//! | [`permission`] | Permission system |
//! | [`protocol`] | Handshake protocol |
//! | [`registry`] | Channel registry |
//! | [`router`] | Message router |
//! | [`serializer`] | Serialization utilities |
//! | [`streaming`] | Streaming framework |
//! | [`transport`] | Transport abstraction and implementations |
//! | [`validator`] | Message validation |
//! | [`wire`] | Wire format and framing |

pub mod auth;
pub mod bus;
pub mod codec;
pub mod config;
pub mod connection;
pub mod diagnostics;
pub mod discovery;
pub mod dispatcher;
pub mod error;
pub mod event;
pub mod guard;
pub mod heartbeat;
pub mod manager;
pub mod message;
pub mod metrics;
pub mod middleware;
pub mod peer;
pub mod permission;
pub mod protocol;
pub mod registry;
pub mod router;
pub mod serializer;
pub mod streaming;
#[cfg(test)]
pub mod testing;
pub mod transport;
pub mod validator;
pub mod wire;

/// Prelude: re-exports the most commonly used types.
pub mod prelude {
    pub use crate::auth::*;
    pub use crate::bus::*;
    pub use crate::config::*;
    pub use crate::connection::*;
    pub use crate::error::*;
    pub use crate::event::BusEvent;
    pub use crate::guard::*;
    pub use crate::heartbeat::*;
    pub use crate::message::*;
    pub use crate::protocol::*;
    pub use crate::transport::*;
    pub use crate::validator::*;
    pub use crate::wire::*;
    pub use lumi_common::ipc::{Channel, LumiMessage, MessageType, ProcessId};
    pub use lumi_common::security::ProcessCapabilities;
}
